type LibExtendsType = {
 $extends?: string; 
};
type LibRecycleType = {
 $recycle?: string; 
};
type ForeignType<T> = {
 $foreign?: { [key: string]: { [key: string]: CssPropsType<T> & CssPseudoJoinedType<T> & CssAddicionalTypes<T> } }; 
};
type CssPropsType<T> = LibExtendsType & LibRecycleType & ForeignType<T> & {
scrollbar_width?: string;
scrollbar_color?: string;
scrollbar_gutter?: string;
scroll_behavior?: string;
scroll_margin?: string;
scroll_padding?: string;
scroll_snap_align?: string;
scroll_snap_stop?: string;
scroll_snap_type?: string;
webkit_scrollbar?: string;
scroll_container?: string;
scrollbar_aria_role?: string;
background?: string;
background_color?: string;
background_image?: string;
background_position?: string;
background_repeat?: string;
background_size?: string;
background_attachment?: string;
background_blend_mode?: string;
background_clip?: string;
background_origin?: string;
border?: string;
border_top?: string;
border_right?: string;
border_bottom?: string;
border_left?: string;
border_radius?: string;
border_width?: string;
border_left_width?: string;
border_right_width?: string;
border_top_width?: string;
border_bottom_width?: string;
border_color?: string;
border_left_color?: string;
border_right_color?: string;
border_top_color?: string;
border_bottom_color?: string;
border_top_left_radius?: string;
border_top_right_radius?: string;
border_bottom_left_radius?: string;
border_bottom_right_radius?: string;
border_style?: string;
border_left_style?: string;
border_top_style?: string;
border_right_style?: string;
border_bottom_style?: string;
outline?: string;
outline_style?: string;
outline_color?: string;
outline_width?: string;
outline_offset?: string;
display?: string;
opacity?: string;
visibility?: string;
overflow?: string;
overflow_x?: string;
overflow_y?: string;
overflow_block?: string;
overflow_inline?: string;
overflow_clip_margin?: string;
flex?: string;
flex_direction?: string;
flex_wrap?: string;
flex_flow?: string;
flex_grow?: string;
flex_shrink?: string;
flex_basis?: string;
justify_content?: string;
justify_items?: string;
align_items?: string;
align_self?: string;
align_content?: string;
order?: string;
gap?: string;
row_gap?: string;
column_gap?: string;
grid?: string;
grid_area?: string;
grid_template?: string;
grid_template_areas?: string;
grid_template_rows?: string;
grid_template_columns?: string;
grid_row?: string;
grid_row_start?: string;
grid_row_end?: string;
grid_column?: string;
grid_column_start?: string;
grid_column_end?: string;
grid_gap?: string;
grid_row_gap?: string;
grid_column_gap?: string;
grid_auto_flow?: string;
grid_auto_rows?: string;
grid_auto_columns?: string;
margin?: string;
margin_left?: string;
margin_right?: string;
margin_top?: string;
margin_bottom?: string;
padding?: string;
padding_left?: string;
padding_right?: string;
padding_top?: string;
padding_bottom?: string;
box_sizing?: string;
box_shadow?: string;
width?: string;
min_width?: string;
max_width?: string;
height?: string;
min_height?: string;
max_height?: string;
position?: string;
top?: string;
right?: string;
bottom?: string;
left?: string;
z_index?: string;
float?: string;
clear?: string;
transform?: string;
transform_origin?: string;
transform_style?: string;
translate?: string;
font?: string;
font_family?: string;
font_size?: string;
font_weight?: string;
font_style?: string;
font_variant?: string;
font_stretch?: string;
font_size_adjust?: string;
font_synthesis?: string;
font_feature_settings?: string;
font_kerning?: string;
font_language_override?: string;
font_optical_sizing?: string;
font_variant_alternates?: string;
font_variant_caps?: string;
font_variant_east_asian?: string;
font_variant_ligatures?: string;
font_variant_numeric?: string;
font_variant_position?: string;
line_height?: string;
letter_spacing?: string;
text_align?: string;
text_decoration?: string;
text_transform?: string;
white_space?: string;
word_break?: string;
word_wrap?: string;
text_overflow?: string;
text_shadow?: string;
text_indent?: string;
text_justify?: string;
text_orientation?: string;
text_rendering?: string;
text_size_adjust?: string;
text_combine_upright?: string;
text_emphasis?: string;
text_emphasis_color?: string;
text_emphasis_position?: string;
text_emphasis_style?: string;
text_decoration_color?: string;
text_decoration_line?: string;
text_decoration_skip?: string;
text_decoration_skip_ink?: string;
text_decoration_style?: string;
text_underline_position?: string;
list_style?: string;
list_style_type?: string;
list_style_position?: string;
list_style_image?: string;
color?: string;
accent_color?: string;
cursor?: string;
pointer_events?: string;
vertical_align?: string;
inset?: string;
inset_block?: string;
inset_block_start?: string;
inset_block_end?: string;
inset_inline?: string;
inset_inline_start?: string;
inset_inline_end?: string;
transition?: string;
transition_property?: string;
transition_duration?: string;
transition_timing_function?: string;
transition_delay?: string;
animation?: string;
animation_name?: string;
animation_duration?: string;
animation_timing_function?: string;
animation_delay?: string;
animation_iteration_count?: string;
animation_direction?: string;
animation_fill_mode?: string;
animation_play_state?: string;
animation_timeline?: string;
appearance?: string;
user_select?: string;
aspect_ratio?: string;
resize?: string;
caret?: string;
caret_animation?: string;
caret_shape?: string;
caret_color?: string;
backdrop_filter?: string;
backface_visibility?: string;
block_size?: string;
writing_mode?: string;
break_before?: string;
break_after?: string;
break_inside?: string;
clip?: string;
clip_path?: string;
clip_rule?: string;
filter?: string;
float_offset?: string;
float_defer?: string;
hyphens?: string;
image_rendering?: string;
image_orientation?: string;
image_resolution?: string;
isolation?: string;
mix_blend_mode?: string;
object_fit?: string;
object_position?: string;
overscroll_behavior?: string;
overscroll_behavior_x?: string;
overscroll_behavior_y?: string;
perspective?: string;
perspective_origin?: string;
scroll_snap_margin?: string;
caption_side?: string;
empty_cells?: string;
fill?: string;
fill_rule?: string;
flood_color?: string;
flood_opacity?: string;
lighting_color?: string;
marker_end?: string;
marker_mid?: string;
marker_start?: string;
shape_rendering?: string;
stop_color?: string;
stop_opacity?: string;
stroke?: string;
stroke_dasharray?: string;
stroke_dashoffset?: string;
stroke_linecap?: string;
stroke_linejoin?: string;
stroke_miterlimit?: string;
stroke_opacity?: string;
mask?: string;
mask_type?: string;
mask_image?: string;
mask_mode?: string;
mask_repeat?: string;
mask_position?: string;
mask_clip?: string;
mask_origin?: string;
mask_size?: string;
mask_composite?: string;
mask_border?: string;
mask_border_source?: string;
mask_border_mode?: string;
mask_border_slice?: string;
mask_border_width?: string;
mask_border_outset?: string;
mask_border_repeat?: string;
$content?: string;
}
type CssAdvancedSelectorsType<T> = {
adjacent?: CssPropsType<T> & { $target: string }
child?: CssPropsType<T> & { $target: string }
descendant?: CssPropsType<T> & { $target: string }
near?: CssPropsType<T> & { $target: string }
concat?: CssPropsType<T> & { $target: string }
column?: CssPropsType<T> & { $target: string }
}
type CssPseudoJoinedType<T> = { $pseudoClasses?: CssPseudoClassesType<T>;
$pseudoElements?: CssPseudoElementsType<T>;
}
type CssAddicionalTypes<T> = {
$advancedSelectors?: CssAdvancedSelectorsType<T>[];
 $mediaQueries?: T;
}
type CssPseudoClassesType<T> = {
fullscreen?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
modal?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
picture_in_picture?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
autofill?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
enabled?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
disabled?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
read_only?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
read_write?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
placeholder_shown?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
default?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
checked?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
indeterminate?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
blank?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
valid?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
invalid?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
in_range?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
out_of_range?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
required?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
optional?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
user_valid?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
user_invalid?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
dir?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
lang?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
any_link?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
link?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
visited?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
local_link?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
target?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
target_within?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
scope?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
playing?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
paused?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
current?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
past?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
future?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
root?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
empty?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
nth_child?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
nth_last_child?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
first_child?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
last_child?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
only_child?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
nth_of_type?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
nth_last_of_type?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
first_of_type?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
last_of_type?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
only_of_type?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
active?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
focus?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
focus_visible?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
focus_within?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
hover?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
is?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
not?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
where?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
has?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
nth_col?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
nth_last_col?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
host?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
host_context?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
defined?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_any?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_any_link?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_focusring?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_full_screen?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_full_screen_ancestor?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_full_screen_document?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_full_screen_element?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_full_screen_root?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_placeholder?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_read_only?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_read_write?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_submit_invalid?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_ui_invalid?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_ui_valid?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_any?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_any_link?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_autofill?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_current?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_full_screen?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_full_screen_ancestor?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_full_screen_document?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_full_screen_element?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_full_screen_root?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_input_placeholder?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_read_only?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_read_write?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_button?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_thumb?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_track?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_track_piece?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_search_cancel_button?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_search_results_button?: CssPropsType<T> & { $target?: string } & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
}
type CssPseudoElementsType<T> = {
before?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
after?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
first_letter?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
first_line?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
selection?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
backdrop?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
placeholder?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
marker?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
spelling_error?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
grammar_error?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
cue?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
cue_region?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
part?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
slotted?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
file_selector_button?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
target_text?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
highlight?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_color_swatch?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_focus_inner?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_list_bullet?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_list_number?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_meter_bar?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_progress_bar?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_range_progress?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_range_thumb?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
moz_range_track?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_inner_spin_button?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_meter_even_less_good_value?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_meter_inner_element?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_meter_optimum_value?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_meter_suboptimum_value?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_progress_bar?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_progress_inner_element?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_progress_value?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_button?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_thumb?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_track?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_scrollbar_track_piece?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_search_cancel_button?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_search_results_button?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_slider_runnable_track?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_slider_thumb?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_resizer?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
webkit_input_placeholder?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
placeholder_shown?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
autofill?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
progress_value?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
progress_bar?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
meter_optimum?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
meter_suboptimum?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
meter_sub_suboptimum?: CssPropsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoElementsType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> } | CssPseudoClassesType<T> & CssAddicionalTypes<T> & { $attributes?: CssAttributesType<T> };
}
type CssAttributesType<T> = {
 [key: string]: CssPropsType<T> & CssAddicionalTypes<T> & CssPseudoJoinedType<T> | {
 [key: string]: CssPropsType<T> & CssAddicionalTypes<T> & CssPseudoJoinedType<T> 
};
}
export type CssGeneratorType<T> = CssPropsType<T> & {
$pseudoClasses?: CssPseudoClassesType<T>;
$pseudoElements?: CssPseudoElementsType<T>;
$mediaQueries?: T;
$attributes?: CssAttributesType<T>;
$advancedSelectors?: CssAdvancedSelectorsType<T>[];
}
